name: loop_golf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Image Handling
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  
  # Responsive Design
  sizer: ^2.0.15
  
  # Storage & Persistence
  shared_preferences: ^2.2.2
  
  # Networking
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  
  # Data Visualization
  fl_chart: ^0.65.0
  
  # UI Enhancement
  fluttertoast: ^8.2.4
  
  # Typography
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Location and Weather
  geolocator: ^10.1.0
  url_launcher: ^6.2.2

  # Supabase Integration
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2

  web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    # Removed non-existent assets/svg/ directory

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700